### ISSUE TITLE
Version 0.4.1.15 Error-Message

### ISSUE THREAD

**Issue by Blackscorp81** [vzhabin/WoWsStatInfo#1]
An error occurred while running UserScript WoWsStatInfo 0.4.1.14, script:

Lang: de
Browser name: Opera
Full version: 31.0.1889.174
Major version: 31
AppName: Netscape
UserAgent: Mozilla/5.0 (Windows NT 10.0; WOW64)
AppleWebKit/537.36 (KHTML, like Gecko)
Chrome/44.0.2403.155 Safari/537.36 OPR/31.0.1889.174

Error: Uncaught TypeError: Cannot read property 'cells' of undefined
URL: http://worldofwarships.eu/de/community/accounts/501436395-Killerfrettchen/#tab=pvp/account-tab-overview-pvp
Line: 836
Column: 31
StackTrace: TypeError: Cannot read property 'cells' of undefined

Please, inform script developer about this error.

**Comment by vzhabin** [comment]
Thank you, soon corrected.
